name: connect
services:
    keycloak:
        container_name: keycloak
        image: "quay.io/keycloak/keycloak:26.6.2"
        command: start-dev
        environment:
            - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
            - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
        ports:
            - "8079:8080"
        depends_on:
            keycloak-db:
                condition: service_healthy

    keycloak-db:
        container_name: keycloak-db
        image: "postgres:latest"
        restart: always
        shm_size: 128mb
        environment:
            - POSTGRES_USER=${KC_POSTGRES_USER}
            - POSTGRES_PASSWORD=${KC_POSTGRES_PASSWORD}
            - POSTGRES_DB=${KC_POSTGRES_DB}
        ports:
            - "5433:5433"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -d ${KC_POSTGRES_DB} -U ${KC_POSTGRES_USER}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - keycloak_postgres_data:/var/lib/postgresql

    backend-db:
        container_name: backend-db
        image: "postgres:latest"
        restart: always
        shm_size: 128mb
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - postgres_data:/var/lib/postgresql

    inmemory:
        container_name: inmemory
        image: "redis:latest"
        ports:
            - "6380:6380"
        # command: redis-server --requirepass ${REDIS_PASSWORD}
        healthcheck:
            test:
                # 패스워드 사용 시 cli 뒤 -a ${REDIS_PASSWORD} 추가
                ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s
        volumes:
            - redis_data:/data

    backend:
        build:
            context: ./back
            dockerfile: Dockerfile.dev
            args:
                - JAR_FILE=build/libs/connect-0.0.1-SNAPSHOT.jar
        ports:
            - 8080:8080
        environment:
            - LOG_LEVEL=debug
            - SPRING_PROFILES_ACTIVE=dev
            # - REDIS_PASSWORD=${REDIS_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - GMAIL_APP_USERNAME=${GMAIL_APP_USERNAME}
            - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
        depends_on:
            backend-db:
                condition: service_healthy
            inmemory:
                condition: service_healthy

    # front:
    #     build:
    #         context: ./front
    #         dockerfile: Dockerfile.dev
    #     image: nextjs-sample:dev
    #     container_name: nextjs-dev
    #     ports:
    #         - "3000:3000"
    #     environment:
    #         # Docker 내부에서 파일 변경 사항이 제대로 감지되도록 함
    #         - WATCHPACK_POLLING=true
    #     develop:
    #         # Compose Watch를 사용하여 파일 동기화를 시작
    #         watch:
    #             - action: sync
    #               path: ./front/app
    #               target: /app/app

    #             - action: sync
    #               path: ./front/components
    #               target: /app/components

    #             # rebuild작업은 package.json파일이 변경될 때 종속성이 다시 설치되도록 함
    #             - action: rebuild
    #               path: ./front/package.json

    #             - action: rebuild
    #               path: ./front/next.config.ts

volumes:
    postgres_data:
    redis_data:
    keycloak_postgres_data:
