spring.application.name=connect

# security
spring.ase.secret-key=${SECERET_KEY}

# timeZone
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSX
spring.jackson.time-zone=UTC

# db
spring.r2dbc.host=${POSTGRES_HOST}
spring.r2dbc.port=5432
spring.r2dbc.database=${POSTGRES_DB}
spring.r2dbc.url=r2dbc:postgresql://postgres:5432/connect
spring.r2dbc.username=${POSTGRES_USER}
spring.r2dbc.password=${POSTGRES_PASSWORD}

spring.jpa.show-sql=true

# logging
logging.level.org.springframework.r2dbc=DEBUG

# 대량 트래픽을 위한 데이터 풀
# spring.r2dbc.pool.initial-size=10
# spring.r2dbc.pool.max-size=50

# keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWT_SET_URI}
spring.security.oauth2.resourceserver.base-url=${KEYCLOAK_BASE_URL}
spring.keycloak.base-url=${KEYCLOAK_BASE_URL}
spring.keycloak.client-id=${KEYCLOAK_CLIENT_ID}
spring.keycloak.username=${KEYCLOAK_USERNAME}
spring.keycloak.password=${KEYCLOAK_PASSWORD}
spring.keycloak.secret-client=${KEYCLOAK_SECRET}
spring.keycloak.gmail-redirect-url=${KEYCLOAK_GMAIL_REDIRECT}
spring.keycloak.github-redirect-url=${KEYCLOAK_GITHUB_REDIRECT}

# redis
spring.data.redis.host=inmemory
spring.data.redis.port=6379
# spring.data.redis.password=${REDIS_PASSWORD}

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_APP_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000