ARG NODE_VERSION=24.14.0-slim

FROM node:${NODE_VERSION} AS dev
WORKDIR /app

COPY --chown=node:node package.json package-lock.json* ./

RUN --mount=type=cache,target=/root/.npm \
    if [ -f package-lock.json ]; then \
        npm ci --no-audit --no-fund; \
    else \
        npm install; \
    fi

COPY --chown=node:node . .

ENV WATCHPACK_POLLING=true
ENV HOSTNAME="0.0.0.0"

# 병목 현상 발견되어 주석 처리 >> RUN chown -R node:node /app
# 병목 로그
# => [dev 6/6] RUN chown -R node:node /app                                               157.2s
# => exporting to image                                                                  173.3s
# => => exporting layers                                                                 105.5s

USER node

EXPOSE 3000

CMD ["sh", "-c", "if [ -f package-lock.json ]; then npm run dev; else npm run dev; fi"]